In [1]:
using Flux
using MLDatasets
using ImageCore

# Grokking Deep Learning

In [2]:
weight = 0.1
lr = 0.01

function neural_network(input, weight)
    prediction = input * weight
end

number_of_toes = [8.5]
win_or_lose_binary = [1]  # Won!

input = number_of_toes[1]
t = win_or_lose_binary[1]

pred = neural_network(input, weight)
error = (pred - t) ^ 2
print(error)

0.022499999999999975

### Hot and cold learning (Simple but Inefficient)


Hot and cold learning means wiggling the weights to see which direction reduces the error
the most, moving the weights in that direction, and repeating until the error gets to 0.

Well, you try both up and down and see which one reduces the error!

### Gradient descent


In [21]:
weight = 0.1

function neural_network(input, weight)
    prediction = input * weight
end

number_of_toes = [8.5]
win_or_lose_binary = [1]  # Won!

input = number_of_toes[1]
goal_pred = win_or_lose_binary[1]

pred = neural_network(input, weight)
error = (pred - goal_pred) ^ 2
∇ = pred - goal_pred
weight∇ = input * ∇
α = 0.01
weight -= weight∇ * α

0.11275

In [43]:
weight, goad_pred, input = (0.0, 0.8, 0.9)

for i in 1:5
    pred = input * weight
    ϵ = (pred - goal_pred) ^ 2
    println("=== Epoch $(i)")
    @show ϵ weight pred
    ∇ = pred - goal_pred
    weight∇ = input * ∇
    weight -= weight∇
end

weight

=== Epoch 1
ϵ = 1.0
weight = 0.0
pred = 0.0
=== Epoch 2
ϵ = 0.03609999999999998
weight = 0.9
pred = 0.81
=== Epoch 3
ϵ = 0.0013032100000000015
weight = 1.071
pred = 0.9639
=== Epoch 4
ϵ = 4.704588100000082e-5
weight = 1.1034899999999999
pred = 0.9931409999999999
=== Epoch 5
ϵ = 1.698356304100287e-6
weight = 1.1096631
pred = 0.9986967899999999


1.110835989

In [65]:
weight, goad_pred, input = (0.0, 0.8, 0.9)
α = 0.5

for i in 1:10
    pred = input * weight
    ϵ = (pred - goal_pred) ^ 2
    println("=== Epoch $(i)")
    ∇ = pred - goal_pred
    @show ϵ weight pred ∇
    weight∇ = input * ∇
    weight -= (α * weight∇)
end

weight

=== Epoch 1
ϵ = 1.0
weight = 0.0
pred = 0.0
∇ = -1.0
=== Epoch 2
ϵ = 0.354025
weight = 0.45
pred = 0.405
∇ = -0.595
=== Epoch 3
ϵ = 0.12533370062500002
weight = 0.71775
pred = 0.645975
∇ = -0.35402500000000003
=== Epoch 4
ϵ = 0.0443712633637656
weight = 0.87706125
pred = 0.789355125
∇ = -0.21064487499999995
=== Epoch 5
ϵ = 0.015708536512357138
weight = 0.97185144375
pred = 0.874666299375
∇ = -0.12533370062500004
=== Epoch 6
ϵ = 0.0055612146387872445
weight = 1.02825160903125
pred = 0.9254264481281249
∇ = -0.07457355187187509
=== Epoch 7
ϵ = 0.0019688090124966493
weight = 1.0618097073735937
pred = 0.9556287366362344
∇ = -0.04437126336376562
=== Epoch 8
ϵ = 0.0006970076106491235
weight = 1.0817767758872883
pred = 0.9735990982985595
∇ = -0.026400901701440493
=== Epoch 9
ϵ = 0.0002467581193600543
weight = 1.0936571816529366
pred = 0.984291463487643
∇ = -0.01570853651235704
=== Epoch 10
ϵ = 8.73585432064442e-5
weight = 1.1007260230834972
pred = 0.9906534207751475
∇ = -0.009346579224852491


1.104931983734681

In [60]:
wsum(a, b) = sum(a .* b)

wsum (generic function with 1 method)

In [64]:
function neural_network(input, weights)
    wsum(input, weights)
end

neural_network (generic function with 1 method)

In [86]:
toes = [8.5 , 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2 , 1.3, 0.5, 1.0]

win_or_lose_binary = [1, 1, 0, 1]

weights = [0.1, 0.1, 0.1]
input = [toes[1], wlrec[1], nfans[1]]

for i in 1:4
    pred = neural_network(input, weights)
    ∇ = pred - win_or_lose_binary[1]
    ϵ = ∇ ^ 2
    α = 0.003
    weight_∇ = input .* weights
    weights = weights .- (weight_∇ .* α)
    println("=== Epoch $(i)")
    @show ϵ α ∇ weights pred
end


=== Epoch 1
ϵ = 0.00122500000000001
α = 0.003
∇ = 0.03500000000000014
weights = [0.09745000000000001, 0.099805, 0.09964]
pred = 1.0350000000000001
=== Epoch 2
ϵ = 0.00016297713906250229
α = 0.003
∇ = 0.01276625000000009
weights = [0.09496502500000001, 0.09961038025, 0.099281296]
pred = 1.01276625
=== Epoch 3
ϵ = 7.944130406129285e-5
α = 0.003
∇ = -0.00891298513749983
weights = [0.0925434168625, 0.09941614000851251, 0.09892388333440001]
pred = 0.9910870148625002
=== Epoch 4
ϵ = 0.0009031110235428149
α = 0.003
∇ = -0.03005180566193677
weights = [0.09018355973250626, 0.09922227853549591, 0.09856775735439617]
pred = 0.9699481943380632


In [96]:
# load full training set
train_x, train_y = MNIST.traindata();

# load full test set
test_x,  test_y  = MNIST.testdata();

## Building a neural network

In [189]:
weights = [0.5, 0.48, -0.7]
α = 0.1

streetlights = [1 0 1; 0 1 1; 0 0 1; 1 1 1; 0 1 1; 1 0 1]
walk_vs_stop = [0 1 0 1 1 0]

for i in 1:20
    println("=== Epoch $(i)")
    total_error = 0
    for (j, row) in enumerate(eachrow(streetlights))
        goal_pred = walk_vs_stop[j]
        pred = wsum(row, weights)
        error = (goal_pred - pred) ^ 2
        total_error += error
        ∇ = pred - goal_pred
        weights = weights .- (α .* (row .* ∇ ))
    end
    @show total_error
end

=== Epoch 1
total_error = 2.6561231104
=== Epoch 2
total_error = 0.9628701776715985
=== Epoch 3
total_error = 0.5509165866836797
=== Epoch 4
total_error = 0.36445836852222424
=== Epoch 5
total_error = 0.2516768662079895
=== Epoch 6
total_error = 0.17797575048089034
=== Epoch 7
total_error = 0.12864460733422164
=== Epoch 8
total_error = 0.09511036950476208
=== Epoch 9
total_error = 0.07194564247043436
=== Epoch 10
total_error = 0.05564914990717743
=== Epoch 11
total_error = 0.04394763937673939
=== Epoch 12
total_error = 0.035357967050948465
=== Epoch 13
total_error = 0.02890700056547436
=== Epoch 14
total_error = 0.023951660591138853
=== Epoch 15
total_error = 0.020063105176016144
=== Epoch 16
total_error = 0.016952094519447087
=== Epoch 17
total_error = 0.014420818295271236
=== Epoch 18
total_error = 0.012331739998443648
=== Epoch 19
total_error = 0.010587393171639842
=== Epoch 20
total_error = 0.009117233405426495


### Backpropagation

In [294]:
hidden_size = 4
weights₀ = 2 * rand(Float64, (3, hidden_size)) .- 1
weights₁ = 2 * rand(Float64, (hidden_size, 1)) .- 1
α = 0.2

relu(x) = (x > 0) * x

relu2deriv(output) = output > 0

streetlights = [1 0 1; 0 1 1; 0 0 1; 1 1 1; 0 1 1; 1 0 1]
walk_vs_stop = [0 1 0 1 1 0]

for epoch in 1:20
    println("=== Epoch $(epoch)")
    total_error = 0
    for (i, row) in enumerate(eachrow(streetlights))
        layer₀ = row'
        goal_pred = walk_vs_stop[i]
        layer₁ = relu.(layer₀ * weights₀)
        
        layer₂ = sum(layer₁ * weights₁)
        
        total_error += (layer₂ - goal_pred) ^ 2
        layer₂∇ = layer₂ - goal_pred
        
        layer₁∇ = (layer₂∇ * weights₁') .* relu2deriv.(layer₁)
        weights₁ -= α * (layer₁' * layer₂∇)
        weights₀ -= α * (layer₀' * layer₁∇)
    end
    @show total_error
end

=== Epoch 1
total_error = 5.402956997437806
=== Epoch 2
total_error = 1.9251309373400844
=== Epoch 3
total_error = 0.8428460921954337
=== Epoch 4
total_error = 0.3566410966847956
=== Epoch 5
total_error = 0.1603395974073259
=== Epoch 6
total_error = 0.09178367336855531
=== Epoch 7
total_error = 0.05437860206554075
=== Epoch 8
total_error = 0.034496313133492953
=== Epoch 9
total_error = 0.020195104522025862
=== Epoch 10
total_error = 0.011630918423517662
=== Epoch 11
total_error = 0.006646104407267865
=== Epoch 12
total_error = 0.003799964968302484
=== Epoch 13
total_error = 0.0021920647615691793
=== Epoch 14
total_error = 0.001286041394114329
=== Epoch 15
total_error = 0.0007730115285601523
=== Epoch 16
total_error = 0.0004790285056091288
=== Epoch 17
total_error = 0.0003074174328568179
=== Epoch 18
total_error = 0.00020475183342557235
=== Epoch 19
total_error = 0.00014148576942701882
=== Epoch 20
total_error = 0.00010117794922473382


### Three-layer network on MNIST

In [142]:
using Flux
using MLDatasets
using ImageCore
using Distributions

p = Binomial(1, 0.5)

one_hot_encoding(x) = Flux.onehotbatch(x, 0:9)
train_size = 2000

train_x, train_y = MNIST.traindata(1:train_size);
test_x, test_y  = MNIST.testdata();

labels = one_hot_encoding(train_y)
test_labels = one_hot_encoding(test_y)

α, iterations =  0.001, 201
hidden_size, pixels_per_image, num_labels = 40, 28 * 28, 10
batch_size = 100

weights₀ = 0.2 * rand(Float16, (pixels_per_image, hidden_size)) .- 0.1
weights₁ = 0.2 * rand(Float16, (hidden_size, num_labels)) .- 0.1

relu(x) = (x > 0) * x

relu2deriv(output) = output > 0

for epoch in 1:iterations
    error, correct = 0, 0
    for i in 1:train_size
        layer₀ = reshape(train_x[:, :, i], 1, 28*28)  # Input
        label = reshape(labels[:, i], 1, 10)

        layer₁ = relu.(layer₀ * weights₀)
        dropout_mask = rand(p, size(layer₁))
        layer₁ = (layer₁ .* dropout_mask) * 2

        layer₂ = layer₁ * weights₁
        error += sum(( label - layer₂ ) .^ 2)
        correct += convert(Int, argmax(layer₂) == argmax(label))

        layer₂∇ = label - layer₂
        layer₁∇ = (layer₂∇ * weights₁') .* relu2deriv.(layer₁)
        layer₁∇ = layer₁∇ .* dropout_mask

        weights₁ += α * (layer₁' * layer₂∇)
        weights₀ += α * (layer₀' * layer₁∇)
    end

    if rem(epoch, 50) == 0
        println("=== Epoch $(epoch)")
        test_size = 10000
        correct /= train_size
        error /= train_size
        @show error correct
        test_error, test_correct = (0.0, 0)
        for i in 1:test_size
            layer₀ = reshape(test_x[:, :, i], 1, 28*28)
            label = reshape(test_labels[:, i], 1, 10)
            layer₁ = relu.(layer₀ * weights₀)
            layer₂ = layer₁ * weights₁
            test_error += sum(( label - layer₂ ) .^ 2)
            test_correct += convert(Int, argmax(layer₂) == argmax(label))
        end
        test_error /= test_size
        test_correct /= test_size
        @show test_error test_correct
    end
end

=== Epoch 50
error = 0.43363680539958976
correct = 0.7665
test_error = 0.33530167442822706
test_correct = 0.8524
=== Epoch 100
error = 0.38558283436807195
correct = 0.8065
test_error = 0.3015177073133007
test_correct = 0.8742
=== Epoch 150
error = 0.34570466776592645
correct = 0.838
test_error = 0.29056989247280834
test_correct = 0.88
=== Epoch 200
error = 0.3309050307048
correct = 0.858
test_error = 0.28204327293173254
test_correct = 0.8847


In [145]:
using Images
using Flux: onecold

function test_model(image)
    layer₀ = reshape(image, 1, 28*28)
    layer₁ = relu.(layer₀ * weights₀)
    layer₂ = layer₁ * weights₁
    argmax(layer₂)[2] - 1
end

n = rand(1:10000, 16)
grid = [
    MNIST.convert2image(test_x[:, :, i])
    for i in n
]
predict, label = [], []

for i in n
    push!(predict, test_model(test_x[:, :, i]))
    push!(label, onecold(test_labels[:, i]) - 1)
end

@show predict label

mosaicview(grid; nrow=1)

predict = Any[3, 1, 5, 3, 1, 8, 4, 9, 7, 7, 1, 6, 6, 0, 8, 2]
label = Any[3, 1, 3, 3, 1, 8, 4, 9, 7, 7, 7, 6, 6, 0, 8, 2]


### Batch training

In [146]:
using Flux
using MLDatasets
using ImageCore
using Distributions

one_hot_encoding(x) = Flux.onehotbatch(x, 0:9)
train_size = 1000

train_x, train_y = MNIST.traindata(1:train_size);
test_x, test_y  = MNIST.testdata();

labels = one_hot_encoding(train_y)
test_labels = one_hot_encoding(test_y)

α, iterations = 0.1, 201
hidden_size, pixels_per_image, num_labels = 128, 28 * 28, 10
batch_size = 100

weights₀ = 0.2 * rand(Float16, (pixels_per_image, hidden_size)) .- 0.1
weights₁ = 0.2 * rand(Float16, (hidden_size, num_labels)) .- 0.1

relu(x) = (x > 0) * x

relu2deriv(output) = output > 0

for epoch in 1:iterations
    error, correct = 0, 0
    for i in 1:batch_size:train_size
        layer₀ = reshape(train_x[:, :, i:i + batch_size - 1], (28*28, batch_size))'
        label = labels[:, i:i + batch_size - 1]'

        layer₁ = relu.(layer₀ * weights₀)
        p = Binomial(1, 0.5)
        dropout_mask = rand(p, size(layer₁))
        layer₁ = (layer₁ .* dropout_mask) .* 2
        layer₂ = layer₁ * weights₁

        # @show size(layer₀) size(layer₁) size(layer₂) size(weights₀) size(weights₁)
        error += sum(( label - layer₂ ) .^ 2)
        correct += sum(convert.(Int, argmax(layer₂, dims=2) .== argmax(label, dims=2)))
        layer₂∇ = (label - layer₂) ./ batch_size
        layer₁∇ = (layer₂∇ * weights₁') .* relu2deriv.(layer₁)
        layer₁∇ = layer₁∇ .* dropout_mask
        weights₁ += α * (layer₁' * layer₂∇)
        weights₀ += α * (layer₀' * layer₁∇)
    end

    if rem(epoch, 50) == 0
        println("=== Epoch $(epoch)")
        test_size = 5000
        correct /= train_size
        error /= train_size
        @show error correct
        test_error, test_correct = (0.0, 0)
        for i in 1:test_size
            layer₀ = reshape(test_x[:, :, i], 1, 28*28)
            label = test_labels[:, i]'
            layer₁ = relu.(layer₀ * weights₀)
            layer₂ = layer₁ * weights₁
            test_error += sum(( label - layer₂ ) .^ 2)
            test_correct += convert(Int, argmax(layer₂) == argmax(label))
        end
        test_error /= test_size
        test_correct /= test_size
        @show test_error test_correct
    end
end

=== Epoch 50
error = 0.37425603499667937
correct = 0.853
test_error = 0.4191010159136493
test_correct = 0.7974
=== Epoch 100
error = 0.2899693723800722
correct = 0.912
test_error = 0.3593513258346201
test_correct = 0.8316
=== Epoch 150
error = 0.25272370040260533
correct = 0.93
test_error = 0.33472305231706106
test_correct = 0.8412
=== Epoch 200
error = 0.214534084315744
correct = 0.959
test_error = 0.322661942996808
test_correct = 0.8472


In [150]:
function test_model(image)
    layer₀ = reshape(image, 1, 28*28)
    layer₁ = relu.(layer₀ * weights₀)
    layer₂ = layer₁ * weights₁
    argmax(layer₂)[2] - 1
end

n = rand(1:10000, 16)
grid = [
    MNIST.convert2image(test_x[:, :, i])
    for i in n
]
predict, label = [], []

for i in n
    push!(predict, test_model(test_x[:, :, i]))
    push!(label, onecold(test_labels[:, i]) - 1)
end

@show predict label

mosaicview(grid; nrow=1)

predict = Any[4, 9, 2, 1, 6, 1, 0, 7, 3, 3, 7, 4, 2, 3, 0, 5]
label = Any[4, 9, 2, 1, 6, 1, 0, 9, 3, 3, 7, 9, 2, 3, 0, 5]


### Upgrading the MNIST network

In [2]:
using Flux
using MLDatasets
using ImageCore
using Distributions

p = Binomial(1, 0.5)

one_hot_encoding(x) = Flux.onehotbatch(x, 0:9)
train_size = 1000

train_x, train_y = MNIST.traindata(1:train_size);
test_x, test_y  = MNIST.testdata();

labels = one_hot_encoding(train_y)
test_labels = one_hot_encoding(test_y)

α, iterations = 2, 101
hidden_size, pixels_per_image, num_labels = 128, 28 * 28, 10
batch_size = 100

weights₀ = 0.02 * rand(Float32, (pixels_per_image, hidden_size)) .- 0.01
weights₁ = 0.2 * rand(Float32, (hidden_size, num_labels)) .- 0.1

tanh2deriv(output) = 1 - (output ^ 2)

for epoch in 1:iterations
    error, correct = 0, 0
    for i in 1:batch_size:train_size
        layer₀ = reshape(train_x[:, :, i:i + batch_size - 1], (28*28, batch_size))'
        label = labels[:, i:i + batch_size - 1]'

        layer₁ = tanh.(layer₀ * weights₀)
        dropout_mask = rand(p, size(layer₁))
        layer₁ = (layer₁ .* dropout_mask) .* 2
        layer₂ = softmax(layer₁ * weights₁, dims=2)
        # @show size(layer₀) size(layer₁) size(layer₂) size(weights₀) size(weights₁)
        error += sum(( label - layer₂ ) .^ 2)
        correct += sum(convert.(Int, argmax(layer₂, dims=2) .== argmax(label, dims=2)))
        layer₂∇ = (label - layer₂) ./ (batch_size * size(layer₁)[1])
        layer₁∇ = (layer₂∇ * weights₁') .* tanh2deriv.(layer₁)
        layer₁∇ = layer₁∇ .* dropout_mask
        weights₁ += α * (layer₁' * layer₂∇)
        weights₀ += α * (layer₀' * layer₁∇)
    end

    if rem(epoch, 20) == 0
        println("=== Epoch $(epoch)")
        test_size = 10000
        correct /= train_size
        error /= train_size
        @show error correct
        test_error, test_correct = (0.0, 0)
        for i in 1:test_size
            layer₀ = reshape(test_x[:, :, i], 1, 28*28)
            label = test_labels[:, i]'
            layer₁ = tanh.(layer₀ * weights₀)
            layer₂ = layer₁ * weights₁
            test_error += sum(( label - layer₂ ) .^ 2)
            test_correct += convert(Int, argmax(layer₂) == argmax(label))
        end
        test_error /= test_size
        test_correct /= test_size
        @show test_error test_correct
    end
end

=== Epoch 20
error = 0.6190143302898572
correct = 0.753
test_error = 2.650810194516497
test_correct = 0.7221
=== Epoch 40
error = 0.3953942164833337
correct = 0.822
test_error = 11.155884094838054
test_correct = 0.7859
=== Epoch 60
error = 0.2904212420385567
correct = 0.862
test_error = 20.351821856372
test_correct = 0.8177
=== Epoch 80
error = 0.23761920310625867
correct = 0.874
test_error = 28.633479336521763
test_correct = 0.8324
=== Epoch 100
error = 0.2026168553027372
correct = 0.892
test_error = 36.10451605569889
test_correct = 0.8422


In [7]:
using Flux: onecold
using Images

function test_model(image)
    layer₀ = reshape(image, 1, 28*28)
    layer₁ = tanh.(layer₀ * weights₀)
    layer₂ = layer₁ * weights₁
    argmax(layer₂)[2] - 1
end

n = rand(1:10000, 16)
grid = [
    MNIST.convert2image(test_x[:, :, i])
    for i in n
]
predict, label = [], []

for i in n
    push!(predict, test_model(test_x[:, :, i]))
    push!(label, onecold(test_labels[:, i]) - 1)
end

@show predict label

mosaicview(grid; nrow=1)

predict = Any[4, 1, 2, 4, 1, 9, 6, 7, 5, 6, 4, 0, 5, 7, 1, 5]
label = Any[4, 1, 2, 4, 1, 5, 6, 7, 5, 6, 4, 0, 3, 7, 1, 5]


In [1]:
using CUDA
CUDA.functional()

true

In [2]:
using Flux, Statistics
using Flux.Data: DataLoader
using Flux: onehotbatch, onecold, @epochs
using Flux.Losses: logitcrossentropy
using Base: @kwdef
using Statistics
using MLDatasets
using ImageCore
using CUDA
using BenchmarkTools

α, iterations = 2, 201
hidden_size, pixels_per_image, num_labels = 128, 28 * 28, 10
batch_size = 100

one_hot_encoding(x) = Flux.onehotbatch(x, 0:9)
train_size = 2500

train_x, train_y = MNIST.traindata(1:train_size);
test_x, test_y  = MNIST.testdata();

x_train, x_test = Flux.flatten(train_x), Flux.flatten(test_x)
labels, test_labels = one_hot_encoding(train_y), one_hot_encoding(test_y)

train_loader = Flux.DataLoader((x_train, labels), batchsize=batch_size, shuffle=true)
test_loader = Flux.DataLoader((x_test, test_labels), batchsize=batch_size)


@show CUDA.functional()
CUDA.allowscalar(false)
device = gpu

function loss_and_accuracy(data_loader, model, device)
    acc = 0
    ls = 0.0f0
    num = 0
    for (x, y) in data_loader
        x, y = device(x), device(y)
        ŷ = model(x)
        ls += logitcrossentropy(ŷ, y, agg=sum)
        acc += sum(onecold(ŷ) .== onecold(y))
        num +=  size(x)[end]
    end
    return ls / num, acc / num
end

model = Chain(
    Dense(784, hidden_size, Flux.relu),
    Dense(hidden_size, num_labels)
) |> device

ps = Flux.params(model)
opt = ADAM(0.0003)


for epoch in 1:iterations
    for (x, y) in train_loader
        x, y = device(x), device(y)
        gs = gradient(() -> logitcrossentropy(model(x), y), ps)
        Flux.Optimise.update!(opt, ps, gs)
    end

    train_loss, train_acc = loss_and_accuracy(train_loader, model, device)
    test_loss, test_acc = loss_and_accuracy(test_loader, model, device)
    if rem(epoch, 50) == 0
        println("Epoch=$epoch")
        println("  train_loss = $train_loss, train_accuracy = $train_acc")
        println("  test_loss = $test_loss, test_accuracy = $test_acc")
    end
end

CUDA.functional() = true
Epoch=50
  train_loss = 0.06743283, train_accuracy = 0.992
  test_loss = 0.30189067, test_accuracy = 0.9097
Epoch=100
  train_loss = 0.01513822, train_accuracy = 1.0
  test_loss = 0.3153039, test_accuracy = 0.9134
Epoch=150
  train_loss = 0.0049137594, train_accuracy = 1.0
  test_loss = 0.34140927, test_accuracy = 0.9151
Epoch=200
  train_loss = 0.0019735906, train_accuracy = 1.0
  test_loss = 0.36677662, test_accuracy = 0.9155


## Neural network that understand language

In [10]:
f = open("reviews.txt")
raw_reviews = filter.(x -> length(x) > 0, unique.(split.(readlines(f), " ")))
close(f)

f = open("labels.txt")
raw_labels = readlines(f)
close(f)

In [11]:
vocab = unique(reduce(vcat, raw_reviews))
word2index = Dict(v => i for (i, v) in enumerate(vocab))
input_dataset = map.(x -> word2index[x], raw_reviews)
labels = map(x -> (x == "positive") ? 1 : 0, raw_labels);

In [12]:
using Flux

train_size = 24000

α, iterations, hidden_size, batch_size = 0.01, 3, 100, 100

weights₀ = 0.2 * rand(Float32, (length(vocab), hidden_size)) .- 0.1
weights₁ = 0.2 * rand(Float32, (hidden_size, 1)) .- 0.1


for epoch in 1:iterations
    total, correct = 0, 0
    for i in 1:train_size
        x, y = input_dataset[i], labels[i]
        
        layer₁ = sigmoid.(sum(weights₀[x, :], dims=1))
        layer₂ = sum(sigmoid.(layer₁ * weights₁))
        layer₂∇ = layer₂ - y
        layer₁∇ = layer₂∇ * weights₁'
        weights₀[x, :] .-= layer₁∇ * α
        weights₁ -= (layer₁' * layer₂∇) * α
        
        if abs(layer₂∇) < 0.5
            correct += 1
        end
        total += 1
    end

    if rem(epoch, 10) != 0
        println("=== Epoch $(epoch)")
        @show correct / total
        test_total, test_correct = (0.0, 0)
        for i in 1:train_size
            x, y = input_dataset[i], labels[i]

            layer₁ = sigmoid.(sum(weights₀[x, :], dims=1))
            layer₂ = sum(sigmoid.(layer₁ * weights₁))
            if abs(layer₂ - y) < 0.5
                test_correct += 1
            end
            test_total += 1
        end
        @show test_correct / test_total
    end
end

=== Epoch 1
correct / total = 0.833875
test_correct / test_total = 0.9093333333333333
=== Epoch 2
correct / total = 0.8998333333333334
test_correct / test_total = 0.9311666666666667
=== Epoch 3
correct / total = 0.9201666666666667
test_correct / test_total = 0.9441666666666667


### Comparing word embeddings

In [25]:
function similar(target="beautiful", len=10)
    target_index = word2index[target]
    scores = Dict()
    for (word, index) in word2index
        ∇ = weights₀[index, :] - weights₀[target_index, :]
        ∇² = ∇ .^ 2
        scores[word] = -sqrt(sum(∇²))
    end
    sort(collect(scores), by=x -> x[2], rev=true)[1:len]
end

similar("beautiful", 15)

15-element Vector{Pair{Any, Any}}:
   "beautiful" => -0.0
      "lonely" => -0.7056556329625407
 "recommended" => -0.7078083581416031
 "spectacular" => -0.7111706962582793
       "magic" => -0.7126587491451116
       "marie" => -0.7391234313687798
      "worlds" => -0.7488965394581588
         "bit" => -0.7497769035517885
     "freedom" => -0.7600134527197082
    "flawless" => -0.7630605198702134
  "underrated" => -0.7642487332774035
        "best" => -0.7654467655313637
   "subtitles" => -0.7681777644865341
       "heart" => -0.7722322816952291
     "certain" => -0.7746179427000939

In [37]:
similar("excellent", 20)

20-element Vector{Pair{Any, Any}}:
   "excellent" => -0.0
     "amazing" => -0.783072247434673
 "wonderfully" => -0.815343526144588
     "perfect" => -0.8190406439823616
        "rare" => -0.8199391127254688
  "incredible" => -0.8300515343199132
        "noir" => -0.8414920201502964
   "wonderful" => -0.8464807060644697
      "superb" => -0.8643986063688696
       "loved" => -0.8905058149461618
  "refreshing" => -0.8954279358300526
   "enjoyable" => -0.8965530446981935
       "today" => -0.8980784862582105
   "perfectly" => -0.9398194042677067
         "gem" => -0.9537147370213367
    "funniest" => -0.9720811391636802
 "fascinating" => -0.9779250115548829
      "highly" => -0.9815329198755685
    "favorite" => -1.0087843929478575
       "solid" => -1.0254972511338174

In [43]:
similar("awful", 20)

20-element Vector{Pair{Any, Any}}:
          "awful" => -0.0
         "poorly" => -0.7705812653972363
          "waste" => -0.8442135471653316
 "disappointment" => -0.9326396910457765
          "worst" => -0.9834540776291226
  "disappointing" => -1.002170864614918
          "lacks" => -1.058728084663763
           "dull" => -1.1268992238986413
          "fails" => -1.187673129960059
         "boring" => -1.1899847943726
           "mess" => -1.195906488924898
          "avoid" => -1.2515626298816966
      "laughable" => -1.2813880657651135
       "terrible" => -1.2819919652546716
          "badly" => -1.2825153160450613
          "worse" => -1.2972612616555865
       "annoying" => -1.3017155674452148
       "horrible" => -1.3903810117546451
      "redeeming" => -1.494150315909755
           "poor" => -1.4996410031702376

### Filling in the blank
##### Learn richer meanings for words by having a richer signal to learn.

This example uses almost exactly the same neural network as the previous one, with only a few
modifications. First, instead of predicting a single label given a movie review, you’ll take each
(five-word) phrase, remove one word (a focus term), and attempt to train a network to figure
out the identity of the word you removed using the rest of the phrase. Second, you’ll use a trick
called negative sampling to make the network train a bit faster.

In [5]:
using Random

In [6]:
f = open("reviews.txt")
raw_reviews = filter.(x -> length(x) > 0, unique.(split.(readlines(f), " ")))
close(f)

f = open("labels.txt")
raw_labels = readlines(f)
close(f)

vocab = unique(reduce(vcat, raw_reviews))
word2index = Dict(v => i for (i, v) in enumerate(vocab))
input_dataset = map.(x -> word2index[x], raw_reviews)
concatenated = reduce(vcat, input_dataset)
shuffle!(input_dataset)
labels = map(x -> (x == "positive") ? 1 : 0, raw_labels);

In [7]:
using Flux: mean, sigmoid


train_size = 24000

α, iterations = 0.05, 3
hidden_size, window, negative = 50, 2, 5

weights₀ = 0.2 * (rand(Float32, (length(vocab), hidden_size)) .- 0.5)
weights₁ = zeros(length(vocab), hidden_size)

layer₂_target = zeros(negative + 1)
layer₂_target[1] = 1

for epoch in 1:iterations
    for (i, review) in enumerate(input_dataset)
        for (j, word_idx) in enumerate(review)
            target_samples = vcat([word_idx], concatenated[rand(1:train_size, negative)])
            left_context = review[max(1, j - window):j-1]
            right_context = review[j+1:min(length(review), j + window)]
            layer₁ = mean(weights₀[vcat(left_context, right_context), :], dims=1)
            layer₂ = sigmoid.(layer₁ * weights₁[target_samples, :]')
            layer₂∇ = layer₂ - layer₂_target'
            layer₁∇ = layer₂∇ * weights₁[target_samples, :]
            weights₀[vcat(left_context, right_context), :] .-= layer₁∇ * α
            weights₁[target_samples, :] -= (layer₁' * layer₂∇)' * α
        end
        if i % 6000 == 0
            println("Progress: $(i/length(input_dataset))")
        end
    end
end

Progress: 0.24
Progress: 0.48
Progress: 0.72
Progress: 0.96
Progress: 0.24
Progress: 0.48
Progress: 0.72
Progress: 0.96
Progress: 0.24
Progress: 0.48
Progress: 0.72
Progress: 0.96


In [8]:
function similar(target="beautiful", len=10)
    target_index = word2index[target]
    scores = Dict()
    for (word, index) in word2index
        ∇ = weights₀[index, :] - weights₀[target_index, :]
  ∇² = ∇ .^ 2
        scores[word] = -sqrt(sum(∇²))
    end
    sort(collect(scores), by=x -> x[2], rev=true)[1:len]
end

similar (generic function with 3 methods)

In [9]:
similar("terrible", 15)

15-element Vector{Pair{Any, Any}}:
    "terrible" => -0.0
    "horrible" => -3.3097364824977396
  "horrendous" => -3.579971729597648
    "dreadful" => -3.5812091035815334
      "woeful" => -3.953273192757975
 "nonexistent" => -4.007442545553331
      "shoddy" => -4.028205975085564
   "atrocious" => -4.03973017730732
        "dire" => -4.183451063085509
      "horrid" => -4.185064581924523
    "passable" => -4.203427356365736
      "patchy" => -4.21012521558722
     "puerile" => -4.217044490482364
   "brilliant" => -4.229107092278999
     "jumbled" => -4.258691062478422

In [10]:
similar("beautiful", 15)

15-element Vector{Pair{Any, Any}}:
     "beautiful" => -0.0
 "juxtaposition" => -3.7550090353131163
         "stoic" => -3.7661147099057706
       "radiant" => -3.790207973071254
     "ravishing" => -3.8204828412299014
       "flaming" => -3.846823219948748
        "somber" => -3.8564405127203787
      "lifelike" => -3.8675046520469447
      "luscious" => -3.8722490363136832
   "arrangement" => -3.875301364737359
        "bubbly" => -3.8871365551471513
     "vivacious" => -3.8986207873937286
          "dark" => -3.8990021166267685
    "gorgeously" => -3.9046447460062894
  "technicolour" => -3.922983824389466

#### Neural networks don’t really learn data; they minimize the loss function.

The choice of loss function determines the
neural network’s knowledge.

The more formal term for an `error function` is a `loss function` or `objective function` (all
three phrases are interchangeable). Considering learning to be all about minimizing a loss
function (which includes forward propagation) gives a far broader perspective on how
neural networks learn. Two neural networks can have identical starting weights, be trained
over identical datasets, and ultimately learn very different patterns because you choose
a different loss function. In the case of the two movie review neural networks, the loss
function was different because you chose two different target values (positive or negative
versus fill in the blank)

### King – Man + Woman ~= Queen

The task of filling in the blank creates word embeddings with interesting
phenomena known as word analogies, wherein you can take the vectors for different words
and perform basic algebraic operations on them.

In [11]:
function analogy(positive=["terrible", "good"], negative=["bad"], len=10)
    norms = sum(weights₀ .^ 2, dims=2)
    norms = reshape(norms, size(norms)[1], 1)
    normed_weights = weights₀ .* norms
    query_vect = zeros(length(weights₀[1, :]))
    for word in positive
        query_vect += normed_weights[word2index[word], :]
    end
    
    for word in negative
        query_vect -= normed_weights[word2index[word], :]
    end
    
    scores = Dict()
    for (word, index) in word2index
        ∇ = weights₀[index, :] - query_vect
        ∇² = ∇ .^ 2
        scores[word] = -sqrt(sum(∇²))
    end
    sort(collect(scores), by=x -> x[2], rev=true)[2:len+1]
end

analogy()

10-element Vector{Pair{Any, Any}}:
    "terrific" => -165.95442603500516
    "revolves" => -166.2563281917494
   "fantastic" => -166.30123391615814
    "terrible" => -166.3048727363301
        "good" => -166.38418944759124
   "wonderful" => -166.51375586937112
       "great" => -166.54442408638104
        "fine" => -166.55153066041277
     "perfect" => -166.5577899098246
 "outstanding" => -166.5939216572792

In [12]:
analogy(["big", "large"], ["small"], 20)

20-element Vector{Pair{Any, Any}}:
      "big" => -207.89386919378092
    "large" => -208.53089064977726
    "major" => -209.20847656174945
      "par" => -209.51079797398125
      "low" => -209.5921421215758
   "bottom" => -209.60442302532417
  "biggest" => -209.69713979470885
  "massive" => -209.7059421052052
 "enormous" => -209.78333074585044
   "rental" => -209.82269079979795
      "box" => -209.86474032331722
   "proper" => -209.98485789573044
 "greatest" => -210.00528997751357
     "wide" => -210.0355564517427
    "giant" => -210.05712404592452
     "high" => -210.06939895366375
     "soft" => -210.07419025745145
   "single" => -210.09380694130283
   "filled" => -210.10660714868362
   "decent" => -210.12894755462403

In [13]:
analogy(["awesome", "bad"], ["good"], 20)

20-element Vector{Pair{Any, Any}}:
         "awful" => -221.41499143769627
     "appalling" => -221.8751880988994
           "bad" => -221.92404526258653
     "atrocious" => -222.17358387971976
  "unbelievable" => -222.17401541410243
       "unfunny" => -222.27795596528725
        "wooden" => -222.33253119712518
    "incoherent" => -222.34435245745195
       "excited" => -222.36231331998277
    "amateurish" => -222.4930040687682
      "terrible" => -222.55067136333196
          "lame" => -222.58926220589964
    "uninspired" => -222.61324757760195
       "abysmal" => -222.63025959067124
 "uninteresting" => -222.63933941389587
    "incredible" => -222.64511527375166
  "embarrassing" => -222.68251023400236
   "predictable" => -222.6847414175989
         "forth" => -222.68593727976275
      "dreadful" => -222.72407417527504

## 12. Neural network that write like Shakespeare
Recurrent layers for variable-length data

### The challenge of arbitrary length

In [167]:
norms = sum(weights₀ .^ 2, dims=2)
norms = reshape(norms, size(norms)[1], 1)
normed_weights = weights₀ .* norms

function make_sent_vect(words)
    indices = map(x -> word2index[x], words)
    vec(mean(normed_weights[indices, :], dims=1))
end

reviews2vectors = map(x -> make_sent_vect(x), raw_reviews);
reviews2vectors = permutedims(hcat(reviews2vectors...));

In [156]:
reviews2vectors = reduce(vcat, reviews2vectors);

size(reviews2vectors)

(1250000,)

In [174]:
using StatsBase: countmap

function reverselookup(d, v)
    for k in keys(d)
        if d[k] == v
            return k
        end
    end
    error("LookupError")
end

function most_similar_reviews(review)
    v = make_sent_vect(review)
    scores = Dict(i => val for (i, val) in enumerate(reviews2vectors * v))
    
    vals = values(scores)
    c = countmap(vals)

    most_similar = []
    for (val, _) in sort(collect(c), by=x -> x[2], rev=true)[1:3]
        idx = reverselookup(scores, val)
        push!(most_similar, raw_reviews[idx])
    end
    most_similar
end

for res in map(x -> join(x[1:50], " "), most_similar_reviews(["ok", "terrible"]))
    println("======")
    println(res)
end

when i got this movie free from my job along with three other similar movies . watched then very low expectations now isn t bad per se you get what pay for it is a tale of love betrayal lies sex scandal everything want in definitely not hollywood blockbuster but
how has this piece of crap stayed on tv long it s terrible . makes me want to shoot someone so fake that is actually worse than a sci fi movie i d rather have stroke watch nonsense remember watching when first came out thought hey could be interesting then
this show comes up with interesting locations as fast the travel channel . it is billed reality but in actuality pure prime time soap opera s tries to use exotic locales a facade bring people into phony contest then proceeds hook viewers on contestants style br also borrows from an


### Using identity vectors to sum word embeddings

You may think identity matrices are useless. What’s the purpose of a matrix that takes a
vector and outputs that same vector? In this case, we’ll use it as a teaching tool to show how
to set up a more complicated way of summing the word embeddings so the neural network
can take order into account when generating the final sentence embedding. Let’s explore
another way of summing embeddings.


### Matrices that change absolutely nothing

In [175]:
using LinearAlgebra

In [180]:
a = [1 2 3]
b = [0.1 0.2 0.3]
c = [-1 -0.5 0]
d = [0 0 0]

i = Matrix(1I, 3, 3)

@show i a * i b * i c * i d * i

i = [1 0 0; 0 1 0; 0 0 1]
a * i = [1 2 3]
b * i = [0.1 0.2 0.3]
c * i = [-1.0 -0.5 0.0]
d * i = [0 0 0]


1×3 Matrix{Int64}:
 0  0  0

In [184]:
this = [2 4 6]
movie = [10 10 10]
rocks = [1 1 1]

@show this + movie + rocks
@show ((this * i) + movie) * i + rocks

this + movie + rocks = [13 15 17]
(this * i + movie) * i + rocks = [13 15 17]


1×3 Matrix{Int64}:
 13  15  17

#### Forward propagation

In [209]:
using Flux: softmax

words = ["yankees", "bears", "braves", "red", "sox", "lose", "defeat", "beat", "tie"]
word_vects = Dict(i => [0.0 0.0 0.0] for i in words)
sent2output = rand(3, length(word_vects))
identity_matrix = Matrix(1.0I, 3, 3)

layer₀ = word_vects["red"]
layer₁ = layer₀ * identity_matrix + word_vects["sox"]
layer₂ = layer₁ * identity_matrix + word_vects["defeat"]

pred = softmax(layer₂ * sent2output, dims=2)

1×9 Matrix{Float64}:
 0.111111  0.111111  0.111111  0.111111  …  0.111111  0.111111  0.111111

In [226]:
y = [1 0 0 0 0 0 0 0 0]

∇ = pred - y
layer₂∇ = ∇ * sent2output'
defeat∇ = layer₂∇ * 1
layer₁∇ = layer₂∇ * identity_matrix'
sox∇ = layer₁∇ * 1
layer₀∇ = layer₁∇ * identity_matrix'
α = 0.01

word_vects["red"] -= layer₀∇ * α
word_vects["sox"] -= sox∇ * α
word_vects["defeat"] -= defeat∇ * α

identity_matrix .-= layer₀ .* layer₁∇ * α
identity_matrix .-= layer₁ .* layer₂∇ * α
sent2output -= layer₂' * ∇ * α

3×9 Matrix{Float64}:
 0.299183  0.168145  0.852319  0.154044  …  0.182136  0.244148  0.0725293
 0.897864  0.522778  0.820588  0.377823     0.464942  0.689668  0.925029
 0.817366  0.181134  0.567171  0.837345     0.527068  0.276205  0.144064

In [227]:
word_vects

Dict{String, Matrix{Float64}} with 9 entries:
  "defeat"  => [-0.0100027 0.0294717 0.0548109]
  "tie"     => [0.0 0.0 0.0]
  "lose"    => [0.0 0.0 0.0]
  "beat"    => [0.0 0.0 0.0]
  "yankees" => [0.0 0.0 0.0]
  "sox"     => [-0.0100027 0.0294717 0.0548109]
  "red"     => [-0.0100027 0.0294717 0.0548109]
  "bears"   => [0.0 0.0 0.0]
  "braves"  => [0.0 0.0 0.0]

#### You have all the tools; let’s train the network on a toy corpus.

In [256]:
function clean(word)
    word = strip(word)
    word = replace(word, r"\s+[\d]+" => "", "\n" => "", r"[.?]" => "")
end

clean("\tbathroom\t1")

"bathroom"

In [498]:
tokens = map.(
    clean, 
    map(x -> x[2:end], split.(readlines("./static/data/tasksv11/en/qa1_single-supporting-fact_train.txt")[1:1000], " "))
)
@show size(tokens)
tokens[1:10, :]

size(tokens) = (1000,)


10×1 Matrix{Vector{String}}:
 ["Mary", "moved", "to", "the", "bathroom"]
 ["John", "went", "to", "the", "hallway"]
 ["Where", "is", "Mary", "bathroom"]
 ["Daniel", "went", "back", "to", "the", "hallway"]
 ["Sandra", "moved", "to", "the", "garden"]
 ["Where", "is", "Daniel", "hallway"]
 ["John", "moved", "to", "the", "office"]
 ["Sandra", "journeyed", "to", "the", "bathroom"]
 ["Where", "is", "Daniel", "hallway"]
 ["Mary", "moved", "to", "the", "hallway"]

In [499]:
vocab = unique(reduce(vcat, tokens))
word2index = Dict(word => i for (i, word) in enumerate(vocab))
words2indices(sentence) = map(x -> word2index[x], sentence);

In [500]:
vocab_len = length(vocab)
embed_size = 10
embed = (rand(vocab_len, embed_size) .- 0.5) * 0.1
recurrent = Matrix(1I, embed_size, embed_size)
start = zeros((1, embed_size))
decoder = (rand(embed_size, vocab_len) .- 0.5) * 0.1
one_hot = Matrix(1I, vocab_len, vocab_len);

In [501]:
function predict(sent)
    layer = Dict("hidden" => start)
    layers = [layer]
    
    loss = 0
    preds = []
    for target_i in 1:length(sent)
        layer = Dict("pred" => softmax(last(layers)["hidden"] * decoder, dims=2))
        loss += -log(layer["pred"][sent[target_i]])
        layer["hidden"] = reshape((last(layers)["hidden"] * recurrent)' + embed[sent[target_i], :], (1, 10))
        push!(layers, layer)
    end
    layers, loss
end
predict(map(x -> word2index[x], ["Mary", "moved", "to", "the", "bathroom"]))

([Dict("hidden" => [0.0 0.0 … 0.0 0.0]), Dict("hidden" => [0.04243500900075005 -0.03157065298572253 … -0.019127070657978775 -0.013729220660951247], "pred" => [0.05263157894736842 0.05263157894736842 … 0.05263157894736842 0.05263157894736842]), Dict("hidden" => [0.05947617670571758 -0.03134713697622341 … -0.02216625033006814 -0.006462289726639314], "pred" => [0.05255912581454881 0.05283835962806805 … 0.052646270054151484 0.052358356514606255]), Dict("hidden" => [0.026244755723235647 0.0031055225310064466 … -0.07124711699858233 -0.0073420897536108365], "pred" => [0.052529845001404424 0.0528472766184669 … 0.05266605177149329 0.05232904326636195]), Dict("hidden" => [-0.009142009740404411 -0.03786494678850315 … -0.08701985069337688 -0.03932719216569696], "pred" => [0.05237165302531646 0.05292822675346737 … 0.05254187947470339 0.05220309747155011]), Dict("hidden" => [0.014656925650682495 -0.047511993109032646 … -0.05522644934889257 -0.00023345162548763648], "pred" => [0.052291101312322216 0.

### Backpropagation with arbitrary length

In [502]:
for epoch in 1:40
    for i in 1:length(tokens)  
        α = 0.001
        sent = words2indices(tokens[i][2:end])
        len = length(sent)
        layers, loss = predict(sent)
        
        for layer_idx in length(layers):-1:1
            layer = layers[layer_idx]
            if layer_idx > 1
                target = sent[layer_idx - 1]
                layer["output∇"] = layer["pred"] - one_hot[target, :]'
                
                new_hidden∇ = layer["output∇"] * decoder'
                if layer_idx == length(layers)
                    layer["hidden∇"] = new_hidden∇
                else
                    layer["hidden∇"] = new_hidden∇ + layers[layer_idx + 1]["hidden∇"] * recurrent'
                end
            else
                target = last(sent)
                layer["hidden∇"] = layers[layer_idx + 1]["hidden∇"] * recurrent'
            end
        end
        
        start -= layers[1]["hidden∇"] * α / len
        
        for (layer_idx, layer) in enumerate(layers[2:end])
            decoder -= layers[layer_idx]["hidden"]' .* layer["output∇"] * α / len
            embed_idx = sent[layer_idx]
            embed[embed_idx, :] -= layers[layer_idx]["hidden∇"]' * α / len
            
            recurrent -= layers[layer_idx]["hidden"]' .* layer["hidden∇"] * α / len
        end
        
        if rem(i, 1000) == 0
            println("Perplexity: $(exp(loss/len))")
        end
    end
end

Perplexity: 19.011440750297293
Perplexity: 18.974382770679195
Perplexity: 18.925668801474448
Perplexity: 18.852162885853076
Perplexity: 18.732288533032015
Perplexity: 18.525510253505157
Perplexity: 18.145149064934145
Perplexity: 17.375841989491132
Perplexity: 15.679406620301663
Perplexity: 13.69908693617188
Perplexity: 12.649445245135222
Perplexity: 11.76793254865784
Perplexity: 11.120110966694744
Perplexity: 10.72879852993606
Perplexity: 10.357723529281486
Perplexity: 9.810597381537782
Perplexity: 8.979607588807095
Perplexity: 7.928116394713861
Perplexity: 6.99502115430651
Perplexity: 6.397554985926519
Perplexity: 5.881598260895798
Perplexity: 5.429404231961539
Perplexity: 5.125858599850172
Perplexity: 4.946045912985343
Perplexity: 4.836281531429737
Perplexity: 4.7576243579310535
Perplexity: 4.693233311204678
Perplexity: 4.6410488429398695
Perplexity: 4.599800555252503
Perplexity: 4.566025416563938
Perplexity: 4.5360317888135695
Perplexity: 4.506437077535431
Perplexity: 4.474265089289

In [510]:
sent_index = 233

l, _ = predict(words2indices(tokens[sent_index]))
println(tokens[sent_index])

for (i, each_layer) in enumerate(l[2:end-1])
    input = tokens[sent_index][i]
    correct = tokens[sent_index][i + 1]
    pred = vocab[argmax(vec(each_layer["pred"]))]
    println("Prev Input: $input\tTrue: $correct\tPred: $pred")
end

["Daniel", "travelled", "to", "the", "bedroom"]
Prev Input: Daniel	True: travelled	Pred: is
Prev Input: travelled	True: to	Pred: to
Prev Input: to	True: the	Pred: the
Prev Input: the	True: bedroom	Pred: bedroom
